# Generated by Django 4.2.6 on 2023-10-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
